spring:
  application:
    name: ec-spring-admin
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  boot:
    admin:
      routes:
        endpoints: env,metrics,trace,dump,jolokia,info,configprops,trace,logfile,refresh,flyway,liquibase,heapdump,loggers,auditevents,hystrix.stream
      turbine:
        clusters: default
        location: http://ec-spring-admin:${turbine.stream.port}
server:
  port: 8040
turbine:
  stream:
    port: 8041
eureka:
  # 在注册中心显示IP
  instance:
    hostname: peer1
    preferIpAddress: true
    # 在注册中心中显示的格式
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    metadata-map:
      user.name: ${security.user.name}
      user.password: ${security.user.password}
  client:
    serviceUrl:
      defaultZone: http://admin:${REGISTRY_SERVER_PASSWORD:password}@peer1:1111/eureka/
security:
  user:
    name: admin
    password: ${MONITOR_SERVER_PASSWORD:admin}













