server:
  port: 8999
spring:
  application:
    name: ec-monitoring

#logging.level.org.springframework.cloud=INFO

turbine:
  aggregator:
    cluster-config: default
  turbine:
    app-config: compute-service
# instance-url-suffix: /hystrix.stream

eureka:
  # 在注册中心显示IP
  instance:
    hostname: peer1
    preferIpAddress: true
    # 在注册中心中显示的格式
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    metadata-map:
      user.name: ${security.user.name}
      user.password: ${security.user.password}
  client:
    serviceUrl:
      defaultZone: http://admin:${REGISTRY_SERVER_PASSWORD:password}@peer1:1111/eureka/
