spring:
  application:
    name: config-server
server:
  port: 7001
# 配置服务注册中心
eureka:
  # 在注册中心显示IP
  instance:
    hostname: peer1
    preferIpAddress: true
    # 在注册中心中显示的格式
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    metadata-map:
      user.name: ${security.user.name}
      user.password: ${security.user.password}
  client:
    serviceUrl:
      defaultZone: http://admin:${REGISTRY_SERVER_PASSWORD:password}@peer1:1111/eureka/

# 在注册中心显示IP
#eureka.instance.preferIpAddress=true
# 在注册中心中显示的格式
#eureka.instance.instance-id=${spring.cloud.client.ipAddress}:${server.port}

# git管理配置
# 配置git仓库位置
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ForThePadipata/Micro-services
          searchPaths: config-repo # 配置仓库路径下的相对搜索位置，可以配置多个
          username: zhuguidongChina # 访问git仓库的用户名
          password: Zhuguidong@008 # 访问git仓库的用户密码
        health:
          enabled: false #关闭健康检查器
# 使用本地配置文件
# spring.profiles.active=native
# 本地配置文件地址
# spring.cloud.config.server.native.searchLocations=classpath:/properties/


#spring:
#  rabbitmq:
#    host: localhost
#    port: 5672
#    username: ob_zhu
#    password: 123456






